version: '3.8'

services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx_load_balancer
    ports:
      - "9999:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-1
      - rinha-api-2
      - rinha-api-3
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

  rinha-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha-api-1
    environment:
      - RUN_VERIFY_PAYMENT_SERVICE=true
      - APP_PORT=3000
      - REDIS_ADDR=redis:6379
      - POSTGRES_URL=postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
      - NATS_URL=nats://nats:4222
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - postgres
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  rinha-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha-api-2
    environment:
      - APP_PORT=3000
      - REDIS_ADDR=redis:6379
      - POSTGRES_URL=postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
      - NATS_URL=nats://nats:4222
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - postgres
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  rinha-api-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha-api-3
    environment:
      - APP_PORT=3000
      - REDIS_ADDR=redis:6379
      - POSTGRES_URL=postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
      - NATS_URL=nats://nats:4222
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - postgres
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: rinha_de_backend
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/sql:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "245MB"
    # command: >
    #   postgres
    #   -c synchronous_commit=off
    #   -c wal_writer_delay=200ms
    #   -c commit_delay=10000
    #   -c fsync=off
    #   -c full_page_writes=off
    #   -c max_wal_size=2GB
    #   -c checkpoint_timeout=30min

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data:
  pgadmin_data:
